/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  scientificSidebar: [{type: 'autogenerated', dirName: '00_scientific'}],
  webProgSidebar: [{type: 'autogenerated', dirName: '01_webprog'}],
  distributedSystemsSidebar: [{type: 'autogenerated', dirName: '02_distributedsystems'}],
  softwareengineeringSidebar: [{type: 'autogenerated', dirName: '03_softwareengineering'}],
  itmanagementSidebar: [{type: 'autogenerated', dirName: '04_itmanagement'}],
  bigdataprogrammingSidebar: [{type: 'autogenerated', dirName: '05_bigdataprogramming'}],
  s4d430sidebar: [{type: 'autogenerated', dirName: '06_s4d430'}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
